// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeurhE6A9jGgK8uKDByx6fJguLT_tDAPA',
    appId: '1:712075237721:web:edd2e24958b76ca3ae5448',
    messagingSenderId: '712075237721',
    projectId: 'pawhereapp',
    authDomain: 'pawhereapp.firebaseapp.com',
    storageBucket: 'pawhereapp.appspot.com',
    measurementId: 'G-K03019GDDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXrD0gwUDK0nQlLPTKPsGMrXLRI_KufbQ',
    appId: '1:712075237721:android:00a18f7ca192c3b5ae5448',
    messagingSenderId: '712075237721',
    projectId: 'pawhereapp',
    storageBucket: 'pawhereapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2mvXuuRIj_vjFyZ4tcjk_g-H1PgdCd8',
    appId: '1:712075237721:ios:b7a48e8bff0302bdae5448',
    messagingSenderId: '712075237721',
    projectId: 'pawhereapp',
    storageBucket: 'pawhereapp.appspot.com',
    iosBundleId: 'com.example.pawhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2mvXuuRIj_vjFyZ4tcjk_g-H1PgdCd8',
    appId: '1:712075237721:ios:b7a48e8bff0302bdae5448',
    messagingSenderId: '712075237721',
    projectId: 'pawhereapp',
    storageBucket: 'pawhereapp.appspot.com',
    iosBundleId: 'com.example.pawhere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeurhE6A9jGgK8uKDByx6fJguLT_tDAPA',
    appId: '1:712075237721:web:079cde582d9fdae1ae5448',
    messagingSenderId: '712075237721',
    projectId: 'pawhereapp',
    authDomain: 'pawhereapp.firebaseapp.com',
    storageBucket: 'pawhereapp.appspot.com',
    measurementId: 'G-KNT1LCHE3T',
  );
}
